profiles:
  desktop:
    repos:
      dunst: default
      bash: default
      fonts: default
      git: default
      i3: default
      nvim: default
      picom: default
      starship: default
      polybar: default
      rofi: default
      tmux: default
      tools: default
      kitty: default
